In [1]:
!pip install pandas
!pip install numpy

Collecting pandas
  Downloading pandas-2.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 138.8 MB/s eta 0:00:00
Downloading numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 151.9 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.3.3 pandas-2.3.2 tzdata-2025.2
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (2.3.3)

In [2]:
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np

In [3]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

In [92]:
df.isnull().sum()/len(df)*100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

In [4]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

In [5]:
# Apply value_counts() on column LaunchSite

In [6]:
 
ccafs_launches = data[data['LaunchSite'] == 'CCAFS SLC 40']
print("Lanzamientos desde CCAFS SLC 40:", len(ccafs_launches))

NameError: name 'data' is not defined

In [7]:
import pandas as pd

# Asegúrate de que el DataFrame 'data' ya esté cargado
# 1. Lanzamientos desde 'CCAFS SLC 40'
ccafs_launches = data[data['LaunchSite'] == 'CCAFS SLC 40']
print("Lanzamientos desde CCAFS SLC 40:", len(ccafs_launches))

# 2. Tasa de éxito
successes = ccafs_launches[ccafs_launches['Outcome'] == 'Success']
success_rate = len(successes) / len(ccafs_launches) * 100
print("Tasa de éxito:", round(success_rate, 2), "%")

# 3. Lanzamientos a órbita geosíncrona (GTO)
gto_launches = data[data['Orbit'] == 'GTO']
print("Lanzamientos a órbita geosíncrona (GTO):", len(gto_launches))

NameError: name 'data' is not defined

In [8]:
 
# 1. Lanzamientos desde 'CCAFS SLC 40'
ccafs_launches = data[data['LaunchSite'] == 'CCAFS SLC 40']
print("Lanzamientos desde CCAFS SLC 40:", len(ccafs_launches))

# 2. Tasa de éxito
successes = ccafs_launches[ccafs_launches['Outcome'] == 'Success']
success_rate = len(successes) / len(ccafs_launches) * 100
print("Tasa de éxito:", round(success_rate, 2), "%")

# 3. Lanzamientos a órbita geosíncrona (GTO)
gto_launches = data[data['Orbit'] == 'GTO']
print("Lanzamientos a órbita geosíncrona (GTO):", len(gto_launches))

NameError: name 'data' is not defined

In [9]:
import pandas as pd

# Asegúrate de que el archivo esté cargado correctamente
# Por ejemplo:
# data = pd.read_csv('dataset_part_1.csv')

# 1. Lanzamientos desde 'CCAFS SLC 40'
ccafs_launches = data[data['LaunchSite'] == 'CCAFS SLC 40']
print("Lanzamientos desde CCAFS SLC 40:", len(ccafs_launches))

# 2. Tasa de éxito
successes = ccafs_launches[ccafs_launches['Outcome'] == 'Success']
success_rate = len(successes) / len(ccafs_launches) * 100
print("Tasa de éxito:", round(success_rate, 2), "%")

# 3. Lanzamientos a órbita geosíncrona (GTO)
gto_launches = data[data['Orbit'] == 'GTO']
print("Lanzamientos a órbita geosíncrona (GTO):", len(gto_launches))

NameError: name 'data' is not defined

In [10]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

In [11]:
 
import pandas as pd

# Cargar el archivo desde el enlace
data = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0321EN-SpaceX/labs/module_1_L2/dataset_part_1.csv")

# Verificar las primeras filas
print(data.head())

HTTPError: HTTP Error 404: Not Found

In [12]:
 
# Mostrar solo las columnas necesarias
print(data[['LaunchSite', 'Outcome', 'Orbit']])

NameError: name 'data' is not defined

In [ ]:
 
import pandas as pd

# Si ya cargaste el archivo como 'data'
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
years = data['Date'].dt.year.dropna().unique()
print("Años cubiertos por el dataset:", sorted(years))

In [104]:
 
df[df['LaunchSite'] == 'CCAFS SLC 40'].shape[0]

55

In [107]:
 
df[df['LaunchSite'] == 'CCAFS SLC 40'].shape[0]

55

In [108]:
 
ccafs = df[df['LaunchSite'] == 'CCAFS SLC 40']
successes = ccafs[ccafs['Outcome'] == 'Success']
len(successes) / len(ccafs) * 100

0.0

In [109]:
df['LaunchSite'].value_counts()

LaunchSite
CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

In [110]:
 
df['Orbit'].value_counts()

SyntaxError: invalid non-printable character U+00A0 (1855599515.py, line 2)

In [111]:
 
# Ver todas las variantes de Outcome relacionadas con ASDS
print(df['Outcome'].value_counts())

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

SyntaxError: invalid non-printable character U+00A0 (64889049.py, line 4)

In [13]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857
5,6,2014-01-06,Falcon 9,3325.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1005,-80.577366,28.561857
6,7,2014-04-18,Falcon 9,2296.000000,ISS,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1006,-80.577366,28.561857
7,8,2014-07-14,Falcon 9,1316.000000,LEO,CCAFS SLC 40,True Ocean,1,False,False,True,NaN,1.0,0,B1007,-80.577366,28.561857
8,9,2014-08-05,Falcon 9,4535.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1008,-80.577366,28.561857
9,10,2014-09-07,Falcon 9,4428.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1011,-80.577366,28.561857

In [ ]:
df.isnull().sum()/len(df)*100

In [113]:
 
# Agrupar por tipo de órbita y resultado de misión
resultado_por_orbita = df.groupby(['Orbit', 'Outcome']).size().reset_index(name='Count')

# Mostrar la tabla
print(resultado_por_orbita)

    Orbit      Outcome  Count
0   ES-L1   True Ocean      1
1     GEO    True ASDS      1
2     GTO   False ASDS      1
3     GTO    None ASDS      1
4     GTO    None None     11
5     GTO    True ASDS     13
6     GTO   True Ocean      1
7     HEO    True ASDS      1
8     ISS   False ASDS      2
9     ISS  False Ocean      1
10    ISS   False RTLS      1
11    ISS    None ASDS      1
12    ISS    None None      3
13    ISS    True ASDS      5
14    ISS   True Ocean      1
15    ISS    True RTLS      7
16    LEO    None None      2
17    LEO   True Ocean      1
18    LEO    True RTLS      4
19    MEO    None None      1
20    MEO    True ASDS      2
21     PO   False ASDS      1
22     PO  False Ocean      1
23     PO    None None      1
24     PO    True ASDS      5
25     PO   True Ocean      1
26     SO    None None      1
27    SSO    True ASDS      2
28    SSO    True RTLS      3
29   VLEO   False ASDS      2
30   VLEO    True ASDS     12

In [114]:
 
# Contar aterrizajes exitosos en naves no tripuladas (ASDS)
df['Outcome'].value_counts().get('True ASDS', 0)

np.int64(41)